//! Spai Notes Slice
pub mod autocomplete;
pub mod dedup_engine;
pub mod dialog_state;
pub mod dialog_views;
pub mod discovery;
pub mod external_editor;
pub mod input_highlighter;
pub mod note;
pub mod note_io;
pub mod note_writer;
pub mod similarity;
pub mod spai_prefixes;
pub mod scratch;
pub mod state;
pub mod state_creation;
pub mod state_edit;
pub mod state_item_actions;
pub mod state_similar_actions;
pub mod storage_format;
pub mod text_cursor;
pub mod text_layout;
pub mod time_utils;
pub mod type_options;
pub mod view;
pub mod viewer_content;

pub use state::SpaiNotesState;
pub use view::render_spai_notes_tab;
